SchoolScheduler/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SchoolScheduler.Models;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace SchoolScheduler.Controllers
{
    public class ActivitiesController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Activities
        public async Task<ActionResult> Index()
        {
            if (!SchoolContext.CanConnect())
                return RedirectToAction("Index", "Error");

            OptionEnum selectedOption = OptionEnum.Rooms;
            if (TempData["selectedOption"] != null)
            {
                selectedOption = (OptionEnum)TempData["selectedOption"];
            }

            var optionList = new OptionList();
            optionList.entities = new List<Entity>();

            switch (selectedOption)
            {
                case OptionEnum.Rooms:
                    optionList.entities = await db.Rooms.Cast<Entity>().ToListAsync();
                    break;
                case OptionEnum.ClassGroups:
                    optionList.entities = await db.ClassGroups.Cast<Entity>().ToListAsync();
                    break;
                case OptionEnum.Subjects:
                    optionList.entities = await db.Subjects.Cast<Entity>().ToListAsync();
                    break;
                case OptionEnum.Teachers:
                    optionList.entities = await db.Teachers.Cast<Entity>().ToListAsync();
                    break;
            }

            int selectedEntityId = Convert.ToInt32(TempData["selectedEntityId"]);
            Entity selectedEntity = optionList.entities.Where(ent => ent.Id == selectedEntityId).SingleOrDefault();
            if (selectedEntity == null)
            {
                if (selectedEntityId > 0 && TempData["ConcurrencyAlert"] == null)
                    TempData["ConcurrencyAlert"] = @"Entity you are trying to select 
                    was already deleted by another user";
                if (optionList.entities.Any())
                    selectedEntity = optionList.entities[0];
                else
                    selectedEntity = new Entity();
            }

            optionList.selectedOption = selectedOption;
            optionList.selectedEntity = selectedEntity;

            var activityLabels = await GenerateLabels(selectedOption, selectedEntity.Id);

            ViewBag.activityLabels = activityLabels;

            ViewBag.optionList = optionList;
            return View();
        }

        [HttpPost]
        public ActionResult SelectOption(OptionEnum selectedOption)
        {
            TempData["selectedOption"] = selectedOption;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult SelectOptionValue(OptionEnum selectedOption, int selectedEntityId)
        {
            TempData["selectedOption"] = selectedOption;
            TempData["selectedEntityId"] = selectedEntityId;
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> ActivityModal(OptionEnum selectedOption, int selectedEntityId, int idx, int slot)
        {

            Slot chosenSlot;
            Entity entity;

            chosenSlot = await db.Slots.FindAsync(slot);
            switch (selectedOption)
            {
                case OptionEnum.Rooms:
                default:
                    entity = await db.Rooms.FindAsync(selectedEntityId);
                    break;
                case OptionEnum.ClassGroups:
                    entity = await db.ClassGroups.FindAsync(selectedEntityId);
                    break;
                case OptionEnum.Teachers:
                    entity = await db.Teachers.FindAsync(selectedEntityId);
                    break;
            }

            ViewBag.concurrencyErrorDetected = false;

            // Selected entity from the dropdown 
            // which was then deleted by another user
            if (entity == null)
            {
                ViewBag.concurrencyErrorDetected = true;
                TempData["ConcurrencyAlert"] = "Selected entity was already deleted by another user";
                entity = new Entity();
            }

            Activity activity = null;
            if (idx > 0)
            {
                activity = await db.Activities
                .Include(activity => activity.Room)
                .Include(activity => activity.ClassGroup)
                .Include(activity => activity.Subject)
                .Include(activity => activity.Teacher)
                .Where(activity => activity.ActivityId == idx)
                .SingleOrDefaultAsync();
            }

            if (activity == null && idx > 0)
            {
                ViewBag.concurrencyErrorDetected = true;
                TempData["ConcurrencyAlert"] = @"The activity your are trying to select 
                was already deleted by another user";
            }
            if (activity == null)
                activity = new Activity();

            activity.SlotId = chosenSlot.SlotId;

            ViewBag.selectedOption = selectedOption;
            ViewBag.selectedEntity = entity;
            ViewBag.idx = idx;

            if (selectedOption != OptionEnum.Rooms)
                ViewBag.Rooms = await db.Rooms
                .Include(r => r.Activities)
                .Where(r => r.Activities.All(a => a.ActivityId == idx || a.SlotId != slot))
                .ToListAsync();
            else
                ViewBag.Rooms = await db.Rooms.ToListAsync();

            if (selectedOption != OptionEnum.ClassGroups)
                ViewBag.ClassGroups = await db.ClassGroups
                    .Include(cg => cg.Activities)
                    .Where(cg => cg.Activities.All(a => a.ActivityId == idx || a.SlotId != slot))
                    .ToListAsync();
            else
                ViewBag.ClassGroups = await db.ClassGroups.ToListAsync();

            ViewBag.Subjects = await db.Subjects.ToListAsync();

            if (selectedOption != OptionEnum.Teachers)
                ViewBag.Teachers = await db.Teachers
                .Include(t => t.Activities)
                .Where(t => t.Activities.All(a => a.ActivityId == idx || a.SlotId != slot))
                .ToListAsync();
            else
                ViewBag.Teachers = await db.Teachers.ToListAsync();

            return PartialView(activity);
        }

        [HttpPost]
        public async Task<ActionResult> ModalAction(OptionEnum selectedOption, int selectedEntityId,
        int activityId, int roomId, int classGroupId, int subjectId, int teacherId, int slotId,
        DateTime timestamp)
        {
            TempData["selectedOption"] = selectedOption;
            TempData["selectedEntityId"] = selectedEntityId;

            if (Request.Form.ContainsKey("deleteButton"))
            {
                await DeleteActivity(activityId, timestamp);
                return RedirectToAction("Index");
            }
            else if (Request.Form.ContainsKey("saveButton"))
            {
                // todo check if these fields are not already deleted
                if (!(
                    await db.Rooms.AnyAsync(r => r.Id == roomId) &&
                    await db.ClassGroups.AnyAsync(cg => cg.Id == classGroupId) &&
                    await db.Subjects.AnyAsync(s => s.Id == subjectId) &&
                    await db.Teachers.AnyAsync(t => t.Id == teacherId
                    )))
                {
                    TempData["ConcurrencyAlert"] = @"Form you are trying to post contains 
                    one or more entities which were already deleted by another user. 
                    Your operation was cancelled.";
                    return RedirectToAction("Index");
                }

                Activity activity = await db.Activities.FindAsync(activityId);
                if (activity == null)
                {
                    // we are adding activity

                    // check if another user concurrently already occupied slot
                    var conflictingActivities = await db.Activities
                    .AnyAsync(a => a.SlotId == slotId
                    && (a.RoomId == roomId || a.ClassGroupId == classGroupId || a.TeacherId == teacherId));
                    if (conflictingActivities)
                    {
                        TempData["ConcurrencyAlert"] = @"The activity you are trying to save are conflicting 
                        with already created one by another user. Your operation was cancelled";
                        return RedirectToAction("Index");
                    }

                    activity = new Activity();
                    await db.Activities.AddAsync(activity);
                }

                try
                {
                    activity.RoomId = roomId;
                    activity.ClassGroupId = classGroupId;
                    activity.SubjectId = subjectId;
                    activity.TeacherId = teacherId;

                    activity.SlotId = slotId;
                    db.Entry(activity).OriginalValues["Timestamp"] = timestamp;

                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    TempData["ConcurrencyAlert"] = @"The activity you are trying to change
                    was already changed by another user. Your operation was cancelled";
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }

        private async Task DeleteActivity(int activityId, DateTime timestamp)
        {
            Activity activityToDelete = await db.Activities.FindAsync(activityId);
            if (activityToDelete != null)
            {

SchoolScheduler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolScheduler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/grid.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolScheduler</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manage" asp-action="Index">Manage
                                panel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Activities"
asp-action="Index">Activities panel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SchoolScheduler - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>